### ISSUE TITLE
Storage.modify(...) does not have parameter for toPath

### ISSUE THREAD

**Issue by dthigpen** [Stevertus/objD#14]
Unlike the Data.modify(...) function the Storage.modify(...) function does not a parameter for the destination Storage path.
Example:
Note the null value produced in the mcfunction code.
Dart code:
`Storage.modify("storage",
  modify: DataModify.set(DataStorage("invtools:storage"),
            fromPath: "someFromValue"));`
mcfunction:
`data modify storage datapack:storage null set from storage datapack:storage someFromValue`

**Comment by Stevertus** [comment]
This will be fixed in 0.3.5. Meanwhile you can use Git as source for your pubspec if this breaks something
```
dependencies:
  kittens:
    git: https://github.com/Stevertus/objD.git
```
And I hope this was just an example, but it is actually better in this case to use Storage.set directly.
