### ISSUE TITLE
Player Inventory access

### ISSUE THREAD

**Issue by GamingInfinite** [Stevertus/objD#23]
Just to be able to access the player inventory to see if they have a given item, then run a command based on that.  If this is already possible please tell me how because I can't tell

**Comment by Stevertus** [comment]
Yes you can use 
```dart
If(Entity.Self(nbt: {'Inventory': [Item(Items.stone).getMap()]}))
```
Yes it might not be obvious, let me know how I can improve it 

More resources: https://objd.stevertus.com/basics/#entity
It is also explained here in depth: https://www.youtube.com/watch?v=6aS3K3khuYI
