### ISSUE TITLE
ScoreTimerModule returns incorrect command with negative value for steps parameter

### ISSUE THREAD

**Issue by AdrianCapacite** [Stevertus/objD#25]
When adding ScoreTimerModule to the Pack and the steps parameter value is negative returns an invalid output command.

To explain shortly, I'll show examples. Below I have the module widget placed in the modules parameter of Pack.
![image](https://user-images.githubusercontent.com/45900436/150614453-da64d35b-ff4e-4d96-bce9-78c39741fa35.png)

Building the pack with the ScoreTimerModule should create:
![image](https://user-images.githubusercontent.com/45900436/150614876-2839f447-0db3-48ef-9ef3-0078bfc2ba16.png)

However, the module creates an invalid command:
![image](https://user-images.githubusercontent.com/45900436/150614867-251c92a9-0cb5-4c7f-8e2d-333ac5df83c6.png)

The solution to this error is to use the modulus operator on the steps parameter in the constructor:
![image](https://user-images.githubusercontent.com/45900436/150614765-d23a8023-0785-4541-80b0-b987a6ef8147.png)

This fix should leave positive values unaffected as it is only setting negative values to positive.

If you'd like me to implement the fix I could contribute to the repo, however, I've only started teaching myself how to contribute to repos owned by others.

**Comment by AdrianCapacite** [comment]
Correction, the modulo on steps should not be in the constructor, it should be in the condition where steps < 0:
![image](https://user-images.githubusercontent.com/45900436/150618648-1c4f0743-bedd-4ccc-bc5c-374b4140df2b.png)

**Comment by Stevertus** [comment]
fixed in version 0.4.5
Thanks for reporting!
