### ISSUE TITLE
Bossbar add command has incorrect syntax

### ISSUE THREAD

**Issue by GoDzViper** [Stevertus/objD#26]
When using the "Bossbar(id)" command it generates incorrectly in the mcfunction file.

instead of generating as:
bossbar add winfred_bb {"text":"winfred_bb"}

it generates:
bossbar add winfred_bb {"text":"winfred_bb}"

the end quotation marks and close curly bracket are switched around causing the mcfunction file to generate with an error

**Comment by Stevertus** [comment]
fixed in version 0.4.5
Thanks for reporting!
