### ISSUE TITLE
Missing the required "name" field. on "pub get"

### ISSUE THREAD

**Issue by apsyll** [Stevertus/objD#3]
`[HelloDart] pub get
Resolving dependencies...
Error on line 2, column 1 of pubspec.yaml: Missing the required "name" field.
  ╷
2 │ ┌ dependencies:  
3 │ └    objd: ^0.2.0
  ╵
exit code 65`

**Comment by d0mmi** [comment]
You need to have a name field in your pubspec.yaml File Like this: 
name: "Put Name here"
dependencies:  
objd: ^0.1.0

**Comment by Stevertus** [comment]
I'll update the documentation for that.
Every dart project needs this unique name

**Comment by AunSyedShah** [comment]
Example:
  dev_dependencies:
  name: "myJS"
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
