### ISSUE TITLE
Using sperate row, column parameters for slots

### ISSUE THREAD

**Issue by feldim2425** [Stevertus/objD#4]
The current way the inventory slot utility functions are called (inv, chest, drop) doesn't make that much sense. To store a Slot as a variable its easier to use the Slot Object and the current way with doubles just makes it harder to write for-loops or store one row or column as constant. I think a better solution would be to simply take 2 arguments (row and column) the only difference it would make in most cases it that people have to write ``,`` instead of ``.``.

**Comment by Stevertus** [comment]
updated in version 0.2.2, Thanks!
