### ISSUE TITLE
Suggestion: Can you add custom block and item creation?

### ISSUE THREAD

**Issue by AwesomeKalin** [Stevertus/objD#7]
I'm currently making a datapack which requires custom blocks and items. Can you please add the option?

**Comment by MASTRIO** [comment]
But there is no way to make custom block and items with a datapack :/

**Comment by AwesomeKalin** [comment]
There is. Using CustomModelData and for blocks, you can use the fireworks and armour stand trick

**Comment by Stevertus** [comment]
Custom Blocks have been added with objD v0.3.3
